---
title: "Fungal Traits analysis of Navalacruz 2021 dataset sampling"
author: "Amara Santiesteban Serrano"
date: " r format(Sys.time(), '%d %B, %Y') "
output: 
  html_document:
    df_print: paged
    pdf_document: default
    word_document: default
  editor_options:
    chunk_output_type: inline
---

**FungalTraits**

```{r}
#install.packages("devtools")
#devtools::install_github("ropenscilabs/datastorr")
#devtools::install_github("traitecoevo/fungaltraits")
library(fungaltraits)
devtools::install_github("brendanf/FUNGuildR", force = TRUE)
```

```{r Uploading FungalTraits database}
fungal_traits <- fungal_traits() #As we can see, the Genus column is clean. However in our dataset every genus name contains a "g__" as a prefix. In order to match both datasets we need to get rid of that prefix:
head(fungal_traits)

Polme_2020 <- Polme_2020_FungalTraits
```

```{r}
vista <- Polme_2020 %>%
  dplyr::filter(GENUS=="Alternaria")
```

```{r Collapse the fungal traits database}
#We want to have a unique row for each Genus. In order to achieve this, we calculate the most frequent value (the mode) for each Genus in terms of each variable:
moda <- function(x) {
  ux <- na.omit(unique(x))
  ux[which.max(tabulate(match(x, ux)))]
}

# Group by Genus: 
fungal_traits_mode <- fungal_traits %>%
  dplyr::group_by(Genus) %>%
  dplyr::summarise(across(everything(), moda), .groups = "drop")
#write.csv(fungal_traits_mode, "fungal_traits_collapsed_moda.csv")
```

```{r Merging databases}
ps1_genus_clean <- as.data.frame(tax_table(ps1_genus)) 
ps1_genus_clean$Genus <- gsub("^g__", "", ps1_genus_clean$Genus)

#Extraction of the abundance matrix
otu_mat_genus <- as.data.frame(as.matrix(otu_table(ps1_genus)))

identical(rownames(ps1_genus_clean), rownames(otu_mat_genus)) #Must be TRUE

# Combine ABUNDANCE AND TAXA dataframes by Genus
df_combined <- cbind(ps1_genus_clean, otu_mat_genus) # OR
# Make rownames explicit
df1 <- otu_mat_genus %>% rownames_to_column(var = "ASV_ID")
df2 <- ps1_genus_clean %>% rownames_to_column(var = "ASV_ID")
# Merge by ID
df_combined <- df1 %>% 
  left_join(df2, by = "ASV_ID")

# Combine this dataframe with the Fungal Traits one
df_traits_final <- df_combined %>%
  dplyr::left_join(
    fungal_traits_mode %>% dplyr::select(Genus, speciesMatched, confidence_fg, growth_form_fg, guild_fg, notes_fg, trophic_mode_fg),  
    by = "Genus"
  )
```

```{r Merging databases with Polme}
Polme_2020$Genus <- Polme_2020$GENUS
Polme_2020_a <- Polme_2020[,c(8:26)]

Polme_merged <- df_combined %>%
  dplyr::left_join(Polme_2020_a, by = "Genus")
```

```{r}
vista <- Polme_merged %>%
  dplyr::filter(Phylum=="p__Mortierellomycota")
```

```{r Evaluation of the confidence level}
asvs_by_confidence <- df_traits_final %>%
  dplyr::group_by(confidence_fg) %>%
  dplyr::summarise(n_ASVs = n_distinct(ASV_ID),
                   .groups = "drop") %>%
  dplyr::mutate(total_ASVs = n_total_asvs,
                perc_ASVs = round((n_ASVs / total_ASVs) * 100, 1)
  )
```

```{r % of matching}
# Matching Genus level
asvs_with_traits <- df_combined %>%
  dplyr::filter(!is.na(Genus)) %>%
  dplyr::filter(Genus %in% unique(Polme_2020$Genus))

# Number of unique ASVs matching
n_matching_asvs <- n_distinct(asvs_with_traits$ASV_ID)
n_total_asvs <- n_distinct(df_combined$ASV_ID)

#Number of unique ASVs with a record for "primery_lifestyle"
asvs_with_lifestyle <- Polme_merged %>%
dplyr::filter(!is.na(primary_lifestyle))
n_matching_lifestyle <- n_distinct(asvs_with_lifestyle$ASV_ID)

cat("Number of ASVs matching with FungalTraits:", n_matching_asvs, "\n")
cat("ASVs with a primary_lifestyle assignment:", n_matching_lifestyle, "\n")
cat("Number of total ASVs:", n_total_asvs, "\n")

# Sum of reads matching Genus level traits
reads_matching <- asvs_with_traits %>%
  dplyr::select(-ASV_ID, -Kingdom, -Phylum, -Class, -Order, -Family, -Genus, -Species) %>%   
  as.matrix() %>%
  sum(na.rm = TRUE)

# Total reads in dataset
total_reads <- df_combined %>%
  dplyr::select(-ASV_ID, -Kingdom, -Phylum, -Class, -Order, -Family, -Genus, -Species) %>%
  as.matrix() %>%
  sum(na.rm = TRUE)

cat("Number of reads matching with FungalTraits:", reads_matching, "\n")
cat("Total number of reads:", total_reads, "\n")

# 42.2% of taxonomic assignment by Genus

###reads/abundance####
# Total abundance (reads) matching
matching_reads <- sum(asvs_with_traits$Abundance, na.rm = TRUE)

# Total reads in dataset
total_reads <- sum(ps1_genus_melted$Abundance, na.rm = TRUE)

# Print results
cat("Total reads matching with FungalTraits:", matching_reads, "\n")
cat("Total reads in dataset:", total_reads, "\n")
cat("Percentage of matching reads:", matching_reads / total_reads * 100, "%\n") #This means that the 42% of ASVs matched with the fungal traits database actually represents 80% of the most abundant ASVs (fungal traits does not have info for our less abundant ASV, which is ok)
```

```{r Guild richness}
# Integrate df_traits_final with metadata
df_long <- Polme_merged %>%
  pivot_longer(
    cols = matches("-FIREFUNGI$"),  
    names_to = "SampleID",
    values_to = "Abundance"
  ) 

ps1_genus_metadata <- as(sample_data(ps1_genus), "data.frame") #With phyloseq objects this is the only way to turn this into a dataframe
ps1_genus_metadata$SampleID <- rownames(ps1_genus_metadata)

df_long_meta <- df_long %>%
  dplyr::left_join(ps1_genus_metadata %>% 
  dplyr::select(SampleID, PLOT, SITE, TRAT2, DEPTH), by = "SampleID")

df_long_meta <- df_long_meta %>%
  dplyr::mutate(Presence = ifelse(Abundance > 0, 1, 0))


### DOES GUILD RICHNESS VARY ACROSS FIRE SEVERITY AND DEPTH? We need a richness number per sample (must include SampleID)
# Compute richness (number of unique taxa) per guild, per fire severity, per depth
richness_per_sample <- df_long_meta %>%
  dplyr::group_by(SampleID, TRAT2, DEPTH, primary_lifestyle) %>%
  dplyr::summarise(Richness = sum(Presence), .groups = "drop")

guild_richness_summary <- richness_per_sample %>%
  dplyr::group_by(TRAT2, DEPTH, primary_lifestyle) %>%
  dplyr::summarise(
    MeanRichness = mean(Richness),
    SDRichness   = sd(Richness),
    se = sd(Richness)/sqrt(n()),
    N = n(),
    .groups = "drop"
  )

### MODELS
richness_per_sampleTOP <- richness_per_sample %>% dplyr::filter(DEPTH=="topsoil")
richness_per_sampleSUB <- richness_per_sample %>% dplyr::filter(DEPTH=="subsoil")

glm_results <- glm(
      Richness ~ TRAT2,
      family = poisson, #negative binomial generalized linear models
      data = filter(richness_per_sampleTOP, primary_lifestyle == "soil_saprotroph"))

Anova(glm_results, type="II")

performance::check_overdispersion(
  glm(Richness ~ TRAT2, family = poisson,
      data = filter(richness_per_sampleTOP,
                    primary_lifestyle == "soil_saprotroph"))
)


posthoc <- glm.nb(Richness ~ TRAT2,
                data = filter(richness_per_sampleTOP,
                primary_lifestyle == "unspecified_saprotroph")
)

multcomp::cld(emmeans(posthoc, ~TRAT2, type="response"), Letters=letters)

### PLOT
selected_guilds <- guild_richness_summary %>%
  dplyr::filter(primary_lifestyle %in% c("ectomycorrhizal", "unspecified_saprotroph", "soil_saprotroph", "litter_saprotroph"))

selected_guilds <- selected_guilds %>%
  dplyr::mutate(
    MeanRichness = as.numeric(MeanRichness),
    se = as.numeric(se)
  )

selected_guilds <- selected_guilds %>%
  mutate(
    TRAT2 = factor(TRAT2, levels = c("UB", "LS", "HS1", "HS2")),
    DEPTH = factor(DEPTH, levels = c("topsoil", "subsoil"))
  )

ggplot(selected_guilds, aes(x = TRAT2, y = MeanRichness, color = primary_lifestyle, group = primary_lifestyle)) +
  geom_point(size = 3.5, alpha=.7, position = position_dodge(width = 0.3)) +
  geom_line(position = position_dodge(width = 0.3), alpha=.4) +
  geom_errorbar(aes(ymin = MeanRichness - se, ymax = MeanRichness + se),
                width = 0.1, position = position_dodge(width = 0.3)) +
  scale_color_manual(values = c("#DD1C77","#8c6bb1","#6baed6", "#0570b0")) +
  facet_wrap(~DEPTH) +
  labs(x = "Fire severity", y = "Mean ASV richness ± SE", color = "Guild") +
  theme_minimal() +
  theme(
    panel.background = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA),
    panel.grid = element_blank(),
    axis.ticks = element_line(color = "black"),
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14),
    legend.position = "none"  
  )
ggsave("guild_richness.png", width = 5, height = 4, dpi = 300)

```

```{r Prep: guild richness for SEM}
richness_wide <- richness_per_sample %>%
  pivot_wider(
    names_from  = primary_lifestyle,
    values_from = Richness,
    values_fill = 0
  )

richness_wide_df  <- richness_per_sample %>%
  dplyr::group_by(SampleID, TRAT2, DEPTH) %>%
  dplyr::summarise(
    ECM_richness  = sum(Richness[primary_lifestyle == "ectomycorrhizal"], na.rm = TRUE),
    LSp_richness = sum(Richness[primary_lifestyle == "litter_saprotroph"], na.rm = TRUE),
    USp_richness  = sum(Richness[primary_lifestyle == "unspecified_saprotroph"], na.rm = TRUE),
    .groups = "drop"
  )

guild_richness_SEM <- left_join(richness_wide_df, metadata_df, by = c("SampleID", "TRAT2", "DEPTH"))
```

```{r Relative guild abundance per fire severity}
## First: relative abundance per sample
df_rel <- df_long_meta %>%
  dplyr::group_by(SampleID) %>%
  dplyr::mutate(RelAbund = Abundance / sum(Abundance)) %>%
  dplyr::ungroup()

df_rel %>% ## Just to make sure the sum of rel abundances per sample = 1
  dplyr::group_by(SampleID) %>%
  dplyr::summarise(Suma_rel = sum(RelAbund))

## Relative abundance per guild per sample
guild_rel <- df_rel %>%
  dplyr::group_by(SampleID, TRAT2, DEPTH, primary_lifestyle) %>%
  dplyr::summarise(RelAbund = sum(RelAbund), .groups = "drop") 

guild_rel %>% ## Just to make sure the sum of rel abundances per guild per sample = 1
  dplyr::group_by(SampleID) %>%
  dplyr::summarise(Suma_rel = sum(RelAbund))

## Summarise to graph
guild_rel_summary <- guild_rel %>%
  dplyr::group_by(TRAT2, DEPTH, primary_lifestyle) %>%
  dplyr::summarise(MeanRelAbund = mean(RelAbund)*100,
                   se = sd(RelAbund)/sqrt(n())*100,
                   .groups = "drop") 

guild_rel_summary %>%  #Normalize each mean within each treatment/depth to make sure in the graph each bar adds to 1
  dplyr::group_by(TRAT2, DEPTH) %>%
  dplyr::mutate(graph_abun = MeanRelAbund / sum(MeanRelAbund))

guild_rel_summary2 <- guild_rel_summary %>%
  dplyr::group_by(TRAT2, DEPTH) %>%
  dplyr::mutate(primary_lifestyle = ifelse(MeanRelAbund < 5, "Other", as.character(primary_lifestyle))) %>%
  ungroup() %>%
  # Summarize again because multiple guilds may become "Other"
  dplyr::group_by(TRAT2, DEPTH, primary_lifestyle) %>%
  dplyr::summarise(
    MeanRelAbund = sum(MeanRelAbund),
    se = sum(se),       # optional; conservative
    .groups = "drop"
  )

guild_rel_summary2$TRAT2 <- ordered(guild_rel_summary2$TRAT2, levels = c("UB", "LS", "HS1", "HS2"))
guild_rel_summary2$DEPTH <- ordered(guild_rel_summary2$DEPTH, levels = c("topsoil", "subsoil"))

mine <- c("#DD1C77",
  "#8c6bb1",
           
          "#C994C7",
          "#2c7fb8",
          "#a6bddb",
          "#9ecae1", 
          "#7F3980")

ggplot(guild_rel_summary2, aes(x = TRAT2, y = MeanRelAbund, fill = primary_lifestyle)) +
  geom_bar(stat = "identity", position = "stack", width=.6) +  # grouped bars
  coord_flip() +
  facet_wrap(~DEPTH, nrow = 1) +
  scale_y_continuous(labels = scales::label_number(suffix = "%")) +
  #scale_fill_brewer(name = "Fungal guild", palette = "Dark2", na.value = "grey50")+
  #scale_fill_viridis_d(name = "Fungal guild", option = "D", na.value = "grey50", direction = -1) +
  scale_fill_manual(values=mine, na.value = "grey60") +
  labs(
    x = "Fire severity treatment",
    y = "Mean relative abundance (%)",
    title = "Relative abundance of fungal guilds by fire severity and soil depth"
  ) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(),
    axis.ticks = element_line(color = "black"),
    strip.background = element_blank(),  # Remove strip background
    axis.text.x = element_text(angle = 0.1, hjust = 1),  # Rotate x-axis labels
    panel.background = element_blank(),  # Remove panel background color
    plot.background = element_blank(),   # Remove plot background color
    legend.position = "none"             # Remove legend
  )
#ggsave("stacked_guilds5.png", width = 8, height = 5, dpi = 300)


```

```{r}
# Assuming 'guild_rel_summary' has Mean relative abundances in decimals (0-1)
guild_summary_table <- guild_rel %>%
  dplyr::group_by(TRAT2, DEPTH, primary_lifestyle) %>%
  dplyr::summarise(
    MeanRelAbund = mean(RelAbund, na.rm = TRUE),
    SDRelAbund = sd(RelAbund, na.rm = TRUE),
    n = n(),
    SE = SDRelAbund / sqrt(n),
    .groups = "drop"
  ) %>%
  # convert to percentage
  dplyr::mutate(
    MeanRelAbund = MeanRelAbund * 100,
    SE = SE * 100
  ) %>%
  arrange(DEPTH, TRAT2, primary_lifestyle)

# View the summary table
vista <- guild_summary_table %>% dplyr::filter(primary_lifestyle=="unspecified_saprotroph")

```

```{r}
vista <- Polme_2020 %>% dplyr::filter(primary_lifestyle=="other")
vista <- df_rel %>% dplyr::filter(Genus=="Linnemannia")
```

```{r DOES RELATIVE ABUNDANCE DIFFER BY SEVERITY AND DEPTH?}

guild_rel_TOP <- guild_rel %>% dplyr::filter(DEPTH=="topsoil")
guild_rel_SUB <- guild_rel %>% dplyr::filter(DEPTH=="subsoil")

lm_results <- lm(RelAbund ~ TRAT2, data = guild_rel_TOP %>% dplyr::filter(primary_lifestyle=="soil_saprotroph")) 
anova(lm_results)
emm <- emmeans(lm_results, pairwise ~ TRAT2)
emm

cld_results <- cld(emm$emmeans, Letters = letters)
cld_results
```

################################################################################

```{r Paleta Neón}
n_colors <- length(unique(ps1melted_traits_clean$guild_fg))
neon_palette <- createPalette(n_colors, seedcolors = c("#FF00FF","#39FF14", "#FF6EC7", "#00FFFF","#FFFF00"), range = c(40, 100))


# Asignar nombres si quieres reproducibilidad
names(neon_palette) <- unique(ps1melted_traits_clean$guild_fg)
```

```{r Visualization: Trophic mode}
ps1melted_traits_clean <- ps1melted_traits %>%
  filter(!is.na(growth_form_fg)) #Keep only entries with values in the column 'guild_fg'

ps1melted_traits_clean$DEPTH <- factor(ps1melted_traits_clean$DEPTH, levels = c("topsoil", "subsoil"))

ps1melted_traits_clean %>%
  dplyr::group_by(Sample, guild_fg, TRAT2, DEPTH) %>%
  dplyr::summarise(RelAbun = sum(Abundance)/n(), .groups = "drop") %>%
  ggplot(aes(x = guild_fg, y = RelAbun, fill = guild_fg)) +
  geom_boxplot(width = 0.6, outlier.size = 0.8, alpha = 0.8) +
  #scale_y_log10() + #Log-transform the TotalAbundance for better visualization
  scale_fill_manual(values = neon_palette) +  
  facet_grid(DEPTH ~ TRAT2, scales = "free_y") +
  theme_bw() +
  theme(
    axis.text.x = element_blank(),  # quitar etiquetas del eje x
    axis.ticks.x = element_blank(),
    panel.grid = element_blank(),
    strip.text = element_text(size = 12),
    legend.position = "bottom",  
    legend.title = element_blank()
  ) +
  labs(x = NULL, y = "Relative Abundance")
#ggsave("FungalTraits_TrophicRelAbun.png")
```

```{r Visualization: Symbiotrophs}
ps1melted_traits_clean <- ps1melted_traits %>%
  filter(!is.na(trophic_mode_fg == "Pathotroph-Symbiotroph"))

ps1melted_traits_clean %>%
  dplyr::filter(trophic_mode_fg == "Pathotroph-Symbiotroph") %>%
  dplyr::group_by(Sample, growth_form_fg, TRAT2, DEPTH) %>%
  dplyr::summarise(TotalAbund = sum(Abundance), .groups = "drop") %>%
  ggplot(aes(x = growth_form_fg, y = TotalAbund, fill = growth_form_fg)) +
  geom_boxplot(width = 0.6, outlier.size = 0.8, alpha = 0.8) +
  scale_y_log10()+
  scale_fill_brewer(palette = "Set2") +
  facet_grid(DEPTH ~ TRAT2) +
  theme_bw() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    panel.grid = element_blank(),
    strip.text = element_text(size = 12),
    #legend.position = "none"
  ) +
  labs(x = NULL, y = "Total abundance of symbiotrophs")
#ggsave("FungalTraits_SymbioForm.png")
```

```{r Trophic summary}
trophic_summary <- ps1melted_traits %>%
  dplyr::group_by(guild_fg) %>%
  dplyr::summarise(total_abundance = sum(Abundance))

# Calculate percentage
trophic_summary <- trophic_summary %>%
  dplyr::mutate(percent = 100 * total_abundance / sum(total_abundance))

ps1melted_traits %>%
  dplyr::group_by(TRAT2, guild_fg) %>%
  dplyr::summarise(Abundance = sum(Abundance), .groups = "drop") %>%
  dplyr::group_by(TRAT2) %>%
  dplyr::mutate(Total = sum(Abundance),
         Percent = 100 * Abundance / Total)

```


```{r Visualization: Pathotrophs}
ps1melted_traits_clean %>%
  dplyr::filter(trophic_mode_fg == "Pathotroph") %>%
  dplyr::group_by(Sample, growth_form_fg, TRAT2, DEPTH) %>%
  dplyr::summarise(TotalAbund = sum(Abundance), .groups = "drop") %>%
  ggplot(aes(x = growth_form_fg, y = TotalAbund, fill = growth_form_fg)) +
  geom_boxplot(width = 0.6, outlier.size = 0.8, alpha = 0.8) +
  #scale_y_log10() +
  scale_fill_brewer(palette = "Set2") +
  facet_grid(DEPTH ~ TRAT2) +
  theme_bw() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    panel.grid = element_blank(),
    strip.text = element_text(size = 12),
    #legend.position = "none"
  ) +
  labs(x = NULL, y = "Total abundance of symbiotrophs")
#ggsave("FungalTraits_PathoForm.png")
```


